all: true
include:
  - 'src/'
exclude: []
clean: true
temp-directory: 'coverage'
report-dir: 'coverage'
skip-full: true
reporter: [json, html, text]
check-coverage: true
# because of graphql-transport-ws
branches: 99
lines: 99
functions: 99
statements: 99
